// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYO0lT9YYRMd4KJ4faUWl7Is0xxa3uC74',
    appId: '1:128356135871:web:4ec3432ab989c2a153670a',
    messagingSenderId: '128356135871',
    projectId: 'car-wash-4d1c6',
    authDomain: 'car-wash-4d1c6.firebaseapp.com',
    storageBucket: 'car-wash-4d1c6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQvGQTJEcBLlSiEqMZ7HbgygNY7iDt3wY',
    appId: '1:128356135871:android:30d9605f53f7c1ff53670a',
    messagingSenderId: '128356135871',
    projectId: 'car-wash-4d1c6',
    storageBucket: 'car-wash-4d1c6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA59dlC_HsrmoqVcHG5b7uuZYHNVrjCut8',
    appId: '1:128356135871:ios:ad8159266ba601f553670a',
    messagingSenderId: '128356135871',
    projectId: 'car-wash-4d1c6',
    storageBucket: 'car-wash-4d1c6.appspot.com',
    androidClientId: '128356135871-9okv2vcgbv0e53td2taehuffjaji409g.apps.googleusercontent.com',
    iosClientId: '128356135871-phvfdv9rnovfblhoq028443dfmc96f5p.apps.googleusercontent.com',
    iosBundleId: 'com.example.quickwash',
  );
}
